jobs: 20
cluster: 
  sbatch
    --parsable 
    -t {resources.time_min} 
    -p inv-iranui-fast,inv-iranui 
    --mem {resources.mem_mb} 
    --cpus-per-task {resources.cpus} 
    --account kima
default-resources: [cpus=2, mem_mb=512, time_min=10]
cluster-cancel: scancel